#%RAML 0.8
title: Sample API

/:
  get:
    responses: 
      200: 
        body: 
          text/html:
            example: |
              <html>hello</html>
/redirect:
  get:
    responses: 
      200: 
        body: 
          text/html:
            example: |
              <html>hello</html>